const empireMaleNames = ["Adalbero","Adelbrand","Adelgis","Adelhard","Adelhelm","Adolar","Adolf","Aimar","Alberich",
    "Albert","Aldo","Alida","Alram","Altmann","Alwin","Anselm","Archibald","Aristeo","Arnfried","Arnold","Arnulf",
    "Arwin","Aschwin","Askan","Astolfo","Baldwin","Bernard","Bernfried","Bernger","Bernward","Bert","Berthold",
    "Bertrad","Bertram","Bertrand","Bodo","Bodobert","Bruno","Burkhard","Clodomiro","Conrad","Curt","Dagobert",
    "Dankmar","Dankrad","Degenhard","Deion","Detlev","Dieter","Dietgard","Dietger","Diethard","Dietmar","Dietrich",
    "Ebbo","Eckbert","Eckhard","Egmont","Egon","Eike","Elmer","Elric","Emmerich","Engelbert","Erfried","Erhard",
    "Ernest","Erwin","Everard","Ewald","Falko","Farald","Filibert","Folke","Frank","Frederick","Friedbert","Friedger",
    "Friedhelm","Friedwart","Friso","GÃ¼nther","Gangolf", "Gaston","Gebhard","Gerald","Gerard","Gerfried","Gerlach",
    "Gernot","Gerolf","Gerwig","Gerwin","Gilbert","Giselher","Gismondo","Godfrey","Gonzalo","Goswin","Gotthard",
    "Gottlieb","Gottschalk","Grimwald","Guerino","Guido","Gundolf","Guntbert","Gunthard","Guntram","Hadebrand",
    "Hademar","Hagen","Harald","Hartbert","Hartmann","Hartmut","Hartwig","Hartwin","Hasso","Hatto","Heimo","Heimrad",
    "Helferich","Helmer","Helmut","Henry","Herbert","Hermann","Herwig","Hildebrand","Hildemar","Hilger","Horst",
    "Hubert","Hugo","Humbert","Hunfried","Ingbert","Ingmar","Ingo","Ingolf","Isebrand","Isenbert","Ivo","Kai","Karl",
    "KlÃ©ber","Korbinian","Kraft","Kunibald","Kunibert","Kuno","Lambert","Lando","Landolf","Landrich","Lanfrank",
    "Laurin","Leonhard","Leopold","Liebhard","Liebwin","Lothar","Lubin","Ludger","Ludolf","Ludwig","Luitwin","Luther",
    "Malte","Manegold","Manfred","Markolf","Markward","Meinhard","Meinolf","Meinrad","Mombert","Neidhard","Norbert",
    "Norman","Notker","Oddone","Oliver","Ortwin","Oswald","Ottfried","Ottmar","Otto","Ottokar","Otwin","Raban","Ralf",
    "Randolf","Raymond","Rayner","Reimar","Reingard","Reinhard","Reinhold","Rembert","Richard","Richmut","Rigoberto",
    "Roald","Robert","Rocco","Roderick","Roger","Roland","Romarich","Romuald","Rudolf","Sachso","Siegbald","Siegbert",
    "Sieger","Siegfried","Sieghard","Siegmar","Siegmund","Siegward","Theobald","Thijmen","Thilo","Till","Ubaldo",
    "Ulrich","Volkbert","Volker","Volkhard","Volkmar","Waldemar","Walfried","Walo","Walter","Waltram","Wedekind",
    "Wendelin","Werner","Wieland","Wigand","Wigbert","Wighard","Wigmar","Wilburg","Wilfried","Wilhard","William",
    "Willibald","Willibert","Wilmar","Winand","Winfried","Witold","Wolf","Wolfgang","Wolfhard","Wolfram","Wunibald",
    "Zelindo"];
const empireFemaleNames = ["Abelarda","Adalgisa","Adela","Adelgunde","Adelheid","Adelhelma","Adelinde","Adolfa","Alberta",
    "Alda","Aldona","Alido","Almut","Alrun","Alwine","Amalberga","Anselma","Arda","Aristea","Arnhild","Arnolda",
    "Asgard","Aubrey","Belinda","Bernharde","Berta","Berthild","Bertille","Bertrada","Bliktrud","Bruna","Brunhilde",
    "Burghild","Burglinde","Carla","Charlotte","Cressida","Diemut","Diethild","Dietlinde","Diomira","Ebba","Edelgard",
    "Edeltraud","Ehrentraud","Eike","Elfrun","Elma","Eloise","Elva","Emery","Engel","Engla","Ernesta","Everarda",
    "Filiberta","Franka","Frauke","Frederika","Friedegund","Geraldine","Gerburg","Gerharde","Gerhild","Gerlinde",
    "Gertrud","Gerwine","Gilberta","Gisela","Gotlinde","Griselda","Gudrun","Guerina","Gunda","Gundelinde","Gunthilde",
    "Hedwig","Heilburg","Heilgard","Heilwig","Helmgard","Helmtraud","Hemma","Henrietta","Herlinde","Hermine","Herta",
    "Hildburg","Hildegard","Hildegunde","Hildrun","Hiltrud","Huberta","Huguette","Hulda","Ida","Inge","Ingfried","Irma",
    "Irmgard","Irmhild","Irmlinde","Irmtraud","Ishilde","Kaja","Kirsa","Klothilde","Konrada","Kriemhild","Kunigunde",
    "Lamberta","Landriche","Leonarda","Leopoldine","Liebgard","Liebtrud","Linda","Linde","Lioba","Livina","Loreley",
    "Louise","Ludgera","Ludwina","Luitgard","Margund","Mathilde","Merlind","Miltrud","Norgard","Nortrud","Notburga",
    "Ortraud","Ortrun","Ostara","Ottilia","Radegundis","Raina","Ramona","Randi","Reinhild","Reinhilde","Riccarda",
    "Richmute","Roberta","Rochelle","Rodina","Rolanda","Romilda","Rosalinde","Rosamunde","Roswitha","Rotraud","Runhild",
    "Saskia","Schwanhilde","Sieghilde","Sieglinde","Sigune","Sunna","Sunnhild","Thusnelda","Ubalda","Ulrike","Ute",
    "Veerle","Walpurga","Waltraud","Wanda","Wendelgard","Wendelina","Wigberta","Wigburg","Wilfriede","Wilhelma",
    "Wiltrud","Yvonne"];
const empireSurnames = ["Aach","Abegg","Abend","Abendroth","Aberbach","Abetz","Abicht","Abs","Abt","Achenbach",
    "Achleitner","Ackner","Adelman","Adler","Adorf","Ahle","Ahrendt","Aichele","Aigner","Albiker","Albrecht","Alt",
    "Alterman","Altermann","Altmann","Altschul","Amann","Ammann","Ammermann","Amsel","Anderle","AnschÃ¼tz","Apel",
    "Apfelbaum","Arendt","Armbruster","Arneth","Arnold","Arnoldi","Aschenbrener","Assing","Auch","Auer","Auerbach",
    "Auernheimer","Auerswald","Auffarth","Augenstein","Augsberger","Aumann","Aumeier","Auspitz","Aust","Austerlitz",
    "BÃ¤cker","BÃ¤hr","BÃ¤r","BÃ¤rwald","BÃ¤umler","BÃ¶ckler","BÃ¶deker","BÃ¶hm","BÃ¶hme","BÃ¶hmer","BÃ¶hnisch",
    "BÃ¶nsch","BÃ¶rner","BÃ¶rngen","BÃ¶ttger","BÃ¶tticher","BÃ¼chel","BÃ¼chner","BÃ¼hl","BÃ¼rger","Baade","Baader",
    "Baar","Baasch","Babo","Bach","Bacharach","Bachmann","Bachmayer","Backer","Backhaus","Baer","Bahnsen","Bahr","Bain",
    "Balmer","Bamberger","Band","Bartels","Bartram","Bartsch","Bartz","Basinger","Bastian","Baten","Bauer",
    "Bauernfeind","Baum","Bauman","Baumann","Baumeister","Baumer","Baumhauer","Baumstein","Bauschinger","Becherer",
    "Bechtel","Bechtholdt","Bechtold","Beck","Becken","Beckenbauer","Becker","Beckermann","Beckers","Beckmann","Beer",
    "Behm","Behr","Behrend","Behrends","Behrendt","Behrmann","Beitz","Bendel","Bennewitz","Berchtold","Bergen","Berger",
    "Bergius","Bergler","Bergmann","Berkel","Berkhoff","Berlepsch","Berlin","Bernauer","Bernbaum","Berninger",
    "Bernstein","Berthold","Bessemer","Bethmann","Beutler","Biel","Bier","Bierbaum","Bierkamp","Bierwirth","Binder",
    "Bing","Binger","Birken","Birnbaum","Bischof","Bischoff","Bitterlich","Bittermann","BlÃ¼cher","Blacher","Blanke",
    "Blankenburg","Blatt","Blattner","Blaustein","Blecher","Bleich","Blobel","Bloch","Blocher","Blomberg","Bluhm",
    "Blum","Blumberg","Blumenberg","Blumenfeld","Blumenkrantz","Blumenthal","Blumentritt","Blumhardt","Bode","Boden",
    "Bodenheimer","Bodenschatz","Bodenstein","Bodmer","Boeckmann","Boehm","Boettcher","Bohlen","Bohm","Bohn","Bolender",
    "Boll","Bopp","Borchers","Bormann","Bornemann","Bott","BrÃ¶tzmann","Brack","Brahm","Brahms","Brandeis","Brandis",
    "Brandler","BrandstÃ¤tter","Brandt","Brauer","Braun","Braunbeck","Braune","Brauner","Braunlich","Braunstein",
    "Brausewetter","Brecher","Brecht","Breitner","Brenner","Breslau","Breslauer","Brestrich","Bretschneider","Breuer",
    "Breytenbach","Brickner","Brockhaus","Brodmann","Bronner","Bronstein","Brosch","Bruckmann","Brugmann","Bruhn",
    "Bruhns","Brunke","Brunner","Buchardt","Buchberger","Buchheim","Buchholz","Buchman","Buchner","Buchtel","Buchwald",
    "Buckler","Buhler","Busch","Busemann","Bussler","Buttmann","Buxbaum","Carstens","Cassirer","Christmann","Clasen",
    "Clauberg","Conzelmann","Corcilius","Cornfeld","Cossmann","Cranz","Creuzburg","Cronenberg","Cullmann","Curschmann",
    "DÃ¶hl","DÃ¶rflinger","DÃ¼mmler","DÃ¼nhaupt","Dahlke","Dahmen","Dahmer","Dahn","Dalman","Daluege","Danneberg",
    "Dannecker","Danzig","Daschner","Dassler","Dedekind","Degen","Degener","Dehne","Dehnert","DeichgrÃ¤ber","DelbrÃ¼ck",
    "Dellinger","Denker","Denzel","Denzinger","Derfflinger","Desch","Dessauer","Destinn","Detmold","Deutsch",
    "Deutscher","Deutschmann","Diederich","Diekwisch","Diemer","Dieterich","Dietrich","Dillinger","Dinter","Dischinger",
    "Distel","Distler","Dittrich","Doerr","Dohna","Dorfmann","Dorn","Drach","Drache","Drachmann","Dreifuss","Drescher",
    "Drewes","Drexler","Dreyfus","Dreyfuss","Drossel","Ducke","Duden","Eberl","Eckstein","Edelmann","Edelstein","Egner",
    "Ehlers","Ehman","Ehmann","Ehrenbaum","Ehrenberg","Ehrenfeld","Ehrenfest","Ehrenpreis","Ehrenreich","Ehrenstein",
    "Ehrhardt","Ehrler","Ehrlinger","Ehrmann","EibenschÃ¼tz","Eich","Eichberg","Eichel","Eichelbaum","Eichenberg",
    "Eichenwald","Eicher","Eichhorn","Eichinger","Eichler","Eichmann","Eichwald","Eicke","Einhorn","Einstein","Eisen",
    "Eisenberg","Eisenberger","Eisenmann","Eisenmenger","Eisenstadt","Eisenstein","Eisner","Ellmenreich","Elser",
    "Elsner","Elssler","Emmerich","Engel","Engelberg","Engelberger","Engelhardt","Engelmann","Engels","Enzenauer",
    "Enzensberger","Erdmann","Erhard","Erlach","Erlbaum","Eschenbach","Escherich","Essen","Esser","Essig","Ettlinger",
    "Eugster","Eulenburg","Euler","FÃ¤hnrich","FÃ¤hrmann","FÃ¼nten","FÃ¼rst","FÃ¼rstenberg","Faas","Fabricius",
    "Faehlmann","Faehrmann","Faerber","Fahr","Fahrenheit","Falck","Falkenberg","Fassbender","Faulhaber","Faulstich",
    "Fechner","Fechter","Fehr","Fehrenbach","Feig","Feigenbaum","Feigenspan","Feilhaber","Fein","Feinberg","Feininger",
    "Feistel","Feit","Felder","Felgenhauer","Fellerer","Fellgiebel","Fellner","Felsenbaum","Fenchel","Fendler","Ferber",
    "Fersen","Feuchtwanger","Feuerstein","Feuerwerker","Feulner","Feyerabend","Fichte","Fichtner","Fieber","Fiedler",
    "Finck","Fincke","Fink","Finke","Finkel","Fisch","Fischart","Fischbacher","Fischbein","Fischer","Fischinger",
    "Fischler","Fitkau","Fittkau","FlÃ¼gel","Fleck","Fleischhacker","Fleischman","Fleischmann","Fleiss","Fleming",
    "Flesch","Florstedt","FrÃ¶hlich","Franck","Francke","Frank","Franke","Frankenburg","Franz","Freisler","Freitag",
    "Frenz","Frenzel","Fresenius","Freudenberg","Freudenberger","Freudenstein","Freudenthal","Freund","Freundel",
    "Freundlich","Frey","Freytag","Fric","Fried","Friedberg","Friedberger","Friedeberg","Friedel","Friedemann","Friedl",
    "Friedrich","Fries","Friesinger","Frisch","Froese","Fromm","Frosch","Frucht","Fuchs","Funke","Furrer","Furstenfeld",
    "FurtwÃ¤ngler","Fux","GÃ¶bel","GÃ¶rder","GÃ¶ring","GÃ¶tz","GÃ¼ldenstÃ¤dt","GÃ¼nzburg","Gaertner","Ganser","Gansz",
    "Ganz","Ganzfried","Gebauer","Gebhardt","Gegenbauer","Gehrig","Gehring","Gehrke","Geier","Geiger","Geller",
    "Gellner","Gerhardt","Gering","Germann","Germar","Gerson","GerstÃ¤cker","Gerstacker","Gerstaecker","Gerstenberg",
    "Gerster","Gerstmann","Gerstner","Geschke","Geschwind","Gesner","Gessler","Gessner","Geyer","Gildemeister","Gilger",
    "Gilges","GlÃ¶ckner","GlÃ¼ck","Glas","Glasser","Glehn","Glockenton","Gmehling","Goebel","Goedde","Goethe",
    "Goldberg","Goldberger","Goldblatt","Goldblum","Goldenberg","Goldfarb","Goldfeld","Goldhaber","Goldreich",
    "Goldscheider","Goldschmidt","Goldstein","Goldwasser","Gollwitzer","Gottesman","Gottfried","Gottlieb","Gottschalk",
    "Gottschall","GrÃ¤bner","GrÃ¼n","GrÃ¼nbaum","GrÃ¼nberg","GrÃ¼nfeld","GrÃ¼nspan","Grabner","Gradl","Graebner","Graf",
    "Gramlich","Grasshoff","Grassl","Grau","Grebel","Greifelt","Grendel","Gressmann","Griebel","Grimminger","Grisbaum",
    "Grob","Grohl","Gross","Grosskopf","Grossman","Groth","Grothmann","Gruber","Grundmann","Grunebaum","Gustloff",
    "Gutenberg","Gutfreund","Gutheil","Guttenberg","Guttmacher","Gyrowetz","HÃ¤berli","HÃ¤mmerli","HÃ¤nel","HÃ¤rig",
    "HÃ¤ring","HÃ¤ussler","HÃ¶ffner","HÃ¶fle","HÃ¶ger","HÃ¶hmann","HÃ¶lder","HÃ¶lderlin","HÃ¶ller","HÃ¶nig",
    "HÃ¶nigberg","HÃ¶nigmann","HÃ¶nigsberg","HÃ¶nigsmann","HÃ¶nigswald","HÃ¶ss","HÃ¶ssler","HÃ¼lsen","Haarmann","Haas",
    "Haass","Haber","Haberkorn","Haberlin","Habermann","Habich","Habicht","Hacke","Hackenholt","Hackl","Haeberle",
    "Haerig","Haering","Haeusser","Hafer","Hagedorn","Hagel","Hagelstein","Hagemeister","Hagmann","Hahn","Hahne",
    "Hahnel","Hahnemann","Halberstam","Hamburg","Hamburger","Hammerl","Hammerschmidt","Hammerstein","Hammesfahr",
    "Handke","Handmann","Hanfstaengl","Hanisch","Hannawald","Hanneman","Hannig","Hansch","Hanselmann","Hantzsch",
    "Happe","Hardt","Harig","Haring","Harms","Harnisch","Harrer","Hartig","Hartjenstein","Hartknoch","Hartl",
    "Hartleben","Hartlieb","Hartmann","Hartstein","Hartwich","Haselberger","Haselrieder","Hasenclever","Hass","Hassel",
    "Hasselbach","Hasselhoff","Hassell","Hasselmann","Hasselvander","Hassler","Hattenberger","Hattendorf","Hauck",
    "Hauer","Hauffe","Haugwitz","Hauke","Hauschka","Hauser","Haushofer","Hausmann","Haussegger","Hauswald","Hautzig",
    "Havenstein","Hebrang","Hecher","Hechler","Hecht","Heck","Hecke","Hecker","Hector","Heerwagen","Heffelfinger",
    "Hegeler","Hegewald","Heidemann","Heiden","Heidenreich","Heider","Heidler","Heidrich","Heilbronn","Heilbronner",
    "Heilmann","Heilmeier","Heilprin","Heim","Heimsoth","Heine","Heinecke","Heineken","Heinemann","Heiner","Heinig",
    "Heinrich","Heinsohn","Heinz","Heisenberg","Heisig","Heissler","Heitler","Heitmann","Heitmeyer","Heitz","Helbig",
    "Heldmann","Heldt","Heller","Hellmann","Hellmuth","Hellwig","Helmke","Hencke","Hengsbach","Hengstler","Henlein",
    "Hennig","Henninger","Henschel","Henze","Henzler","Hepner","Herber","Herberger","Herbig","Herder","Herdrich",
    "HergenrÃ¶ther","Herig","Hering","Herkenhoff","Hermann","Herr","Herreshoff","Herrlein","Hersch","Herschel",
    "Herschlag","Hersh","Hertel","Hertner","Hertrich","Hertzberg","Hertzfeld","Hertzog","Herwig","Herz","Herzberg",
    "Herzfeld","Herzig","Herzog","Herzsprung","Hess","Hesse","Hessel","Hettich","Hettinger","Hetz","Heuberger",
    "Heumann","Heun","Heuser","Heydrich","Hielscher","Hilbert","Hildebrandt","Hillebrand","Hilscher","Himmelblau",
    "Himmelfarb","Himmler","Hinrichs","Hippler","Hirsch","Hirschl","Hirtreiter","Hitzig","Hochberg","Hochheim",
    "Hochmeister","Hoehman","Hoehmann","Hoelder","Hoelscher","Hoenigberg","Hoenigsberg","Hoess","Hofbauer","Hoffman",
    "Hoffmann","Hoffmeister","Hofmeister","Hofstetter","Hohenlohe","Hohenstein","Hohmann","Holderbaum","Holderman",
    "Holdermann","Holighaus","Holthusen","Holtz","Holtzmann","Holweck","Holz","Holzer","Holzhausen","Homann","Homburg",
    "Homrighausen","Honig","Honigberg","Honigman","Honigmann","Honigsberg","Honigsman","Honigsmann","Hopf","Hopfer",
    "Hopfner","Horkheimer","Horn","Hornberger","Hornbostel","Horstmann","Huber","Huhn","Huppert","Husch","Hutto",
    "Huwyler","Idelson","Imhoff","JÃ¤ger","JÃ¼rgens","Jahn","Jahnke","Janke","Jentzsch","Joachim","Johner","Jonas",
    "Jonke","Jost","Josten","Jung","Junkermann","KÃ¤ndler","KÃ¤stner","KÃ¤utner","KÃ¶hler","KÃ¶ler","KÃ¶nig","KÃ¶ppen",
    "KÃ¶rte","KÃ¶rver","KÃ¶stler","KÃ¶stner","KÃ¼chler","KÃ¼hn","KÃ¼hne","KÃ¼mmel","KÃ¼nneth","KÃ¼nstler","KÃ¼rschner",
    "KÃ¼ttner","Kachel","Kadelburg","Kahl","Kahler","Kahn","Kaiser","Kalkbrenner","Kallenbach","Kaltenbrunner",
    "Kammerer","Kampf","Kamphaus","Kant","Kantner","Kantorowicz","Kaplan","Kapp","Kapsner","Kasper","Kass","Kassebaum",
    "Katterfeld","Katz","Katzen","Katzenbach","Katzmann","Kaufmann","Kaulbach","Kaulen","Kaulitz","Kautz","Kayserling",
    "Kehlmann","Kehrer","Keilberth","Keiner","Keitel","Keller","Kellermann","Kellner","Kempf","Kepler","Keppler",
    "Kersting","Kesselman","Kesselring","Kessler","Kestenbaum","Ketterer","Keyserling","Kieber","Kiefer","Kieffer",
    "Kielholz","Kiesel","Kiesewetter","Kiesinger","Kiesling","Kindl","Kindler","Kippenberger","Kipping","Kirchner",
    "Kirchweger","Kirchwey","Kirsch","Kirschbaum","Kirschenbaum","Kirstein","Kisling","Kissling","Kistler","Kittel",
    "KlÃ¼gmann","Klaproth","Klauber","Klebs","Klee","Kleiber","Klein","Kleiner","Kleinfeld","Kleinheisterkamp",
    "Kleinman","Kleinmann","Klemm","Klemme","Klemperer","Klempner","Klengel","Klepper","Kling","Klinger","Klinghoffer",
    "Klippel","Klopfer","Klopp","Klopstock","Klostermann","Klotz","Kluck","Kluckhohn","Klugman","Klugmann","Knacke",
    "Knauer","Knirsch","Knoerr","Kober","Koch","Kocher","Koegel","Koehler","Koehne","Koeppen","Kogler","Kohl",
    "Kohlberg","Kohlhaase","Kohlhase","Kohlmann","Kohnstamm","Kohring","Kolb","Kollmann","Korholz","Korn","Kornberg",
    "Kornblum","Kornfeder","Kornfeld","Korngold","KornhÃ¤usel","Korsch","Kossmann","Kott","Kottmann","KrÃ¤mer",
    "KrÃ¼ger","Kracht","Krahl","Krakouer","Krampitz","Kranefuss","Krantz","Kranz","Kratochwil","Kraus","Krause",
    "Krauser","Krauss","Krausser","Krauszer","Krebs","Krehl","Kreisel","Kremers","Krenkel","Kresge","Kresinger",
    "Kretschmer","Kreutzberg","Kreutzwald","Krieger","Krier","Kringel","Krist","Kroeger","Kroemer","Kroll","Kromer",
    "Kronenberg","Kronthaler","Kruckenberg","Krueger","Kruger","Krukenberg","Kruspe","Kuchler","Kuechler","Kuhn",
    "Kummer","Kunst","Kuntz","Kupferblum","Kurrat","Kuttner","LÃ¶ffler","LÃ¶w","LÃ¼thi","Laar","Lachner","Lachs",
    "Lafrenz","Lampadius","Landau","Landauer","Landsberg","Landsberger","Landsteiner","Lang","Lange","Lasch","Lasker",
    "Lattke","Latzke","Laube","Lauer","Laufer","Lauterbach","Lay","Lechner","Lehman","Lehmann","Lehmbruck","Lehmkuhl",
    "Lehner","Lehning","Lehr","Lehrer","Leiber","Leiner","Leistner","Leitgeb","Leitner","Lemann","Lemberger","Lemmer",
    "Lerch","Lerche","Lerner","Lettmann","Letzel","Leupold","Lewisohn","Lexer","Lexis","Licht","Lichtenberger",
    "Lichtenfels","Lichtenstein","Lichter","Lichtwark","Liebehenschel","Lieber","Liebermann","Lieblein","Lilienthal",
    "Lindauer","Lindemann","Lindenbaum","Lindenlaub","Lindner","Lindwurm","Lingenfelter","Linse","Lippert","Lips",
    "Lischke","Lissauer","Littauer","Lobe","Lochte","Loeb","Loewe","LohmÃ¼ller","Lohmiller","Loos","Loosli","Lorber",
    "Lorenz","Lotz","Lowenstam","Ludecke","Ludwig","Lulling","Lustenberger","Lutz","Lux","Luxenberg","MÃ¶hring",
    "MÃ¼ller","MÃ¼nch","MÃ¼nchberg","MÃ¼ntefering","MacNicol","Macher","Madelung","Mader","Madritsch","Mahlau","Mahler",
    "Maibaum","Maier","Mair","Maisel","Mallwitz","Mandelbaum","Mandl","Mangels","Mangold","Mann","Mannheim",
    "Mannheimer","Manteuffel","Marks","Martin","Marx","Masing","Masur","Mathesius","Matthes","Maurer","Mauss","May",
    "Mayenburg","Mayer","Mayr","Mayrhofer","Meckler","Meidner","Meindl","Meissner","Mencken","Mengelberg","Mengele",
    "Menke","Mensing","Mergenthaler","Merkel","Mertz","Merz","Messerschmidt","Metternich","Metze","Metzger","Metzinger",
    "Meyer","Meyr","Miete","Mittag","Mitter","Mittermaier","Mittermeier","Mohnhaupt","Mohr","Moldenhauer","Molitor",
    "Mommsen","Morgentaler","Morgenthau","Moritz","Moser","Mozart","Much","Mucke","Mueller","Muff","Mummert","Muntz",
    "MusÃ¤us","Myers","Myrthenbaum","NÃ¤gelein","Nachtigal","Nachtigall","Nadelman","Nadelmann","Nadler","Nagelberg",
    "Naumann","Nebe","Neff","Nemetz","Nessel","Nesselrode","Nessler","Neubauer","Neubert","Neuer","Neufeld",
    "Neugebauer","NeuhÃ¤user","NeuhÃ¤usser","Neuhaeuser","Neuhaeusser","Neuhaus","Neuheuser","Neumann","Neumark",
    "Neumayer","Neuner","Nickel","Niebuhr","Niedenthal","Niedermayer","Niedermeyer","Niehaus","Niekisch","Niemeyer",
    "Niephaus","Nimitz","Nitzsch","Noffke","Noske","Nosske","Nostitz","Nothnagel","Nottebohm","Nowitzki","Nussbaum",
    "Ober","Oberhauser","Oberlander","Obst","Ochs","Ochsner","OehlenschlÃ¤ger","Oesau","Ohlendorf","Ohly","Olberding",
    "Olbrich","Oldenberg","Opitz","Oppelt","Oppenheim","Oppert","Oppolzer","Orndorff","Ortmann","Osswald","Osterhaus",
    "Otto","Outman","PÃ¶ge","PÃ¶lzl","PÃ¶pel","PÃ¼ckler","Paasche","Pabst","Palitzsch","Palme","PalotÃ¡s","Pankau",
    "Panzer","Panzinger","Parler","Pasche","Pauli","Peltzer","Pelzer","Peters","Petzold","Peucker","Peukert","Pfaff",
    "Pfeffer","Pfefferberg","Pfeiffer","Pfennig","Pfister","Pfisterer","Pfitzner","Pichler","Pickler","Pilc","Pilcz",
    "Piltz","Pilz","Pilzer","Platz","Plesner","Plessner","Pohl","Poland","PollmÃ¤cher","Porsche","Posse","Potthast",
    "PrÃ¶ll","Pracht","Prager","Prantl","Preis","Preisner","Preiss","Preissner","Preiszner","Priesner","Proch",
    "Prochnow","Pruefer","Quaschny","Quattlebaum","Quint","RÃ¤dler","RÃ¶dl","RÃ¶hr","RÃ¶sch","RÃ¶sler","RÃ¶thke",
    "RÃ¼hl","RÃ¼hle","Raab","Raabe","Rabe","Raddatz","Rademacher","Rader","Radnitz","Radnitzer","Raedler","Rahmer",
    "Rahner","Ramberg","Rasch","Rasche","Rathenau","Ratzenberger","Ratzinger","Raupach","Rausch","Rauschenberg",
    "Rauscher","Rechcigl","Reder","Redler","Redlich","Reeder","Reger","Rehberg","Rehder","Rehn","Reich","Reichart",
    "Reichen","Reichenau","Reichenbach","Reichleitner","Reichmann","Reichwein","Reimann","Reimold","Reinhard",
    "Reinhardt","Reinhart","Reinmann","Reiter","Reitter","Reitz","Reubke","Reuter","Rheingold","Ribbeck","Ribbentrop",
    "Richter","Rickenbacker","Riedel","Riederer","Riegel","Rieger","Riehl","Riemann","Riemenschneider","Riesch","Riess",
    "Riesz","Rimensberger","Rinder","Ritschel","Ritter","Robisch","Rodenberg","Roehr","Roemheld","Rogge","Rohmer",
    "Rohr","Rohrbach","Rohrmann","Romberg","Rommel","Rorer","Rosen","Rosenbaum","Rosenberger","Rosenblatt","Rosenblum",
    "Rosenbluth","Rosenfeld","Rosengart","Rosengarten","Rosenhain","Rosenkranz","Rosenstock","Rosenthal","Rosenzweig",
    "Rosin","Ross","Rossel","Rossmann","Roth","Rothberg","Rothenstein","Rothman","Rothmann","Rott","Rottmann",
    "Rottmanner","Rowohlt","Rozenkwit","Rudel","Ruhl","Rutter","SÃ¶llner","Sacher","Sachs","Sack","Sackler","Saft",
    "Saks","Salzer","Samter","Sanner","Sattler","Saudek","Sauer","Sauerbeck","Sauerbruch","Sauerbrunn","Sauerland",
    "Saxer","SchÃ¤dler","SchÃ¶ler","SchÃ¶ll","SchÃ¶n","SchÃ¶nau","SchÃ¶nbaum","SchÃ¶nbeck","SchÃ¶nbein","SchÃ¶nberger",
    "SchÃ¶nborn","SchÃ¶ner","SchÃ¶nfeld","SchÃ¶nfinkel","SchÃ¶nfisch","SchÃ¶nherr","SchÃ¶nlein","SchÃ¶pfer",
    "SchÃ¼nemann","SchÃ¼rer","SchÃ¼rmann","SchÃ¼tz","SchÃ¼tzenberger","Schaab","Schaber","Schachner","Schachtschneider",
    "Schaefer","Schaeffer","Schantz","Schanz","Schaper","Scharf","Scharff","Scharwenka","Schatz","Schau","Schauer",
    "Schauerte","Schaumann","Schaus","Schechter","Scheck","Schedl","Scheerbart","Scheffel","Scheffler","Scheibel",
    "Scheid","Scheidel","Scheidemann","Scheider","Scheiner","Scheller","Schellscheidt","Schenk","Scherer","Scherler",
    "Scherrer","Scherzer","Scherzinger","Scheu","Scheuer","Scheuermann","Scheurer","Schichau","Schickedanz",
    "Schickendantz","Schiefer","Schieffer","Schiele","Schierokauer","Schiff","Schiffer","Schiffner","Schild",
    "Schildenfeld","Schilder","Schildhauer","Schildknecht","Schildkraut","Schiller","Schilling","Schillinger","Schimpf",
    "Schimpff","Schimscheiner","Schindler","Schinkel","Schirlitz","Schirmer","SchlÃ¼ter","Schlag","Schlamme",
    "Schlechter","Schleibaum","Schleiermacher","Schlesinger","Schlessinger","Schlick","Schlim","Schlitz","Schlosser",
    "Schmadel","Schmeichel","Schmeller","Schmerling","Schmetterling","Schmid","Schmidt","Schmidtke","Schmied",
    "Schmiedeberg","Schmitt","Schmitz","Schmuck","Schnabel","Schneider","Schneiderman","Schnell","Schneller",
    "Schnitzer","Schnitzler","Schnorr","Schnyder","Schober","Schock","Schoeler","Schoenauer","Schoenberg","Schoenherr",
    "Schoff","Scholl","Scholz","Schopenhauer","Schor","Schott","Schottel","Schottenstein","SchrÃ¶pfer","SchrÃ¶tter",
    "Schrade","Schreber","Schreck","Schreiber","Schreiner","Schrempf","Schricker","Schroth","Schubert","Schuerer",
    "Schuhbeck","Schulberg","Schulhof","Schulhoff","Schulman","Schult","Schulte","Schultz","Schultze","Schulz",
    "Schulze","Schumacher","Schumann","Schur","Schurz","Schuster","Schutte","Schuttler","Schutz","Schwan","Schwann",
    "Schwanthaler","Schwartz","Schwartzman","Schwartzmann","Schwarz","Schwarzenbach","Schwarzenberger","Schwarzenegger",
    "Schwarzkopf","Schwarzman","Schwarzmann","Schwefel","Schwegler","Schweiger","Schweinitz","Schwender",
    "Schwerdtfeger","Schwerin","Schwerner","Schwertfeger","Schwertner","Schwortz","Seck","Seckbach","Seeliger",
    "Seelman","Seelmann","Seger","Segert","Sehlman","Sehlmann","Seidel","Seiden","SeidenstÃ¼cker","Seidl","Seiler",
    "Seitz","Selig","Semmelrogge","Semmler","Sendler","Senger","Sepp","Seppelt","Sessler","Seydel","Seyfried","Seyler",
    "Siegel","Siemens","Silberbauer","Simmel","Simon","Simson","Singer","Slesinger","Sommer","Sommerfeld","Sondheim",
    "Sonnenfeld","SpÃ¶rl","Spahn","Spahr","Spanner","Specht","Speck","Speckmann","Speidel","Spener","Sperber","Sperl",
    "Sperling","Spiegel","Spiegelmann","Spiegler","Spielberg","Spielmann","Spies","Spiess","Spindler","Spitz","Spitzer",
    "Sprecher","Springborn","Springer","StÃ¤bler","StÃ¶cker","StÃ¼ber","Stadler","StadtbÃ¤umer","Staebler","Staffel",
    "Stahl","Stahlecker","Stahnke","Stamm","Stanger","Stangl","Starck","Starker","Stassen","Staudenmaier","Staudinger",
    "Stauffer","Steichen","Steimle","Stein","Steinbach","Steinbacher","Steinbauer","Steinberg","Steinberger","Steiner",
    "SteinhÃ¤user","SteinhÃ¤usl","SteinhÃ¤usser","Steinhaeuser","Steinhaeusser","Steinhauer","Steinhauser","Steinheil",
    "Steinitz","Steinmeyer","Steinsaltz","Steitz","Stellwagen","Stelzner","Stemmler","Stengel","Stengelin","Stentz",
    "Stenzel","Steppuhn","Stern","Sternberg","Sternberger","Sternhell","Stettin","Steuermann","Steyer","Stickler",
    "Stieler","Stier","Stirner","Stock","Stocker","Stockert","Stockhausen","Stockmann","Stoiber","Stoltenberg","Storch",
    "Storl","Stosch","Strasburg","Strasburger","Strassmann","Straube","Strauch","Strauss","Straussler","Streckenbach",
    "Strecker","Streicher","Stricker","Strittmatter","Strobel","Strobl","Stromberg","Strub","Stuhr","Stumpfegger",
    "Suckow","Suhren","Sulzberger","Sulzer","Sundermann","Surmann","Sussman","Tangemann","Tanne","Tanneberger","Tannen",
    "Tanzer","Tarr","Taschner","Taube","Tauber","Taubert","Taubman","Tausch","Tausche","Tauscher","Taussig","Tegeler",
    "Teicher","TeichmÃ¼ller","Teller","Tendler","Teschner","Tetzlaff","Teyber","ThÃ¤lmann","Thalberg","Thalmann",
    "Theil","Theiner","Theismann","Thiel","Thielemann","Thierse","Thimig","Thoma","Thomalla","Thomas","Thorn",
    "Tiedemann","Tietjen","Tilgner","Tillich","Tisch","Tischbein","Tischendorf","Tischer","Tischler","Tischner",
    "Toman","Totleben","Traeger","Traub","Traube","Trausch","Trauth","Treich","Treitschke","Tugendhat","Turnau",
    "Uebelhoer","Ueberroth","Uffermann","Uhlmann","Uiberreither","Ullmann","Ullmer","Ullrich","Ulmer","Umlauf",
    "Ungar","Unger","Ungerer","Ungers","Unterberger","Untermann","Uthman","Vahlen","Van Houten","Veidt","Veiel",
    "Veil","Vetter","Viermetz","Vieweg","Visscher","Vogel","Vogelstein","Vogelweide","Vogt","Voight","Voigt","Voit",
    "Vom Bruch","Von Bingen","Von Bothmer","Von Braun","Von Cocceji","Von Hardenberg","Von Meyer","Von Sydow",
    "Von Weber","Vonhof","Vorgrimler","WÃ¤chter","WÃ¤chtler","WÃ¶hler","WÃ¶lfflin","Wach","Wachs","Wachsmuth",
    "Wachtel","Wachter","Wachtler","Wackernagel","Wagenknecht","Wagenseil","Wagner","Wahl","Wahle","Wahler","Wahrmann",
    "Waibel","Walbaum","Walch","Wald","WaldmÃ¼ller","Waldmann","Waldner","Waldow","Waldschmidt","Waldstein","Walker",
    "Wall","Wallmann","Wallner","Wandesleben","Wank","Wanka","Wasser","Wassermann","Waxman","Weber","Wechsler",
    "Wegener","Wegmann","Wegner","Wegscheider","Wehausen","Wehinger","Wehner","Weide","Weideman","Weidemann",
    "Weidenmann","Weider","Weidmann","Weidner","Weigl","Weigle","Weinbacher","Weinbaum","Weinberg","Weinberger",
    "Weindorf","Weiner","Weinfeld","Weingaertner","Weingand","Weingart","Weingartner","Weininger","Weinmann",
    "Weinreb","Weinreich","Weinstein","Weinstock","Weintraub","Weinwurm","Weis","Weisgerber","Weishaupt","Weiskopf",
    "Weiss","Weisser","Weisskopf","Weisz","Weitz","Weitzmann","Weiz","Weizenbaum","Weizmann","Welcker","Welker",
    "Weller","Wellmann","Welser","Wendl","Wendland","Wendlinger","Weninger","Wentz","Wentzel","Wenz","Wenzel","Wepper",
    "Werdin","Werfel","Werich","Werkner","Wernicke","Wernz","Wertheim","Werthner","Weschler","Wessely","Westermann",
    "Westheimer","Wetter","Wexler","Wexner","Weyrauch","Wichterle","Wickler","Widmann","Wiedemann","Wiedenfeld",
    "Wiedermann","Wiener","Wieseltier","Wieser","Wiesner","Wieters","Wildner","Wilhelm","Wilpert","Wimpffen","Windisch",
    "Windischmann","Winkelhock","Winkler","Winter","Wintsch","Winzer","Wirth","Wirths","Wirz","Wissmann","Wittgenstein",
    "Wittich","Witting","Wittke","Woerfel","Wolf","Wolfensohn","Wolff","Wolfsohn"];
const dwarfMaleNames = ["Alaric","Aldin","Alrik","Barundin","Belegurn","Boki","Brokk","Bronn","Brynnoth","Burlok","Daled",
    "Deldric","Dimzad","Dorin","Dramar","Drong","Durak","Durk","Dwinbar","Elmador","Enlag","Fimbur","Furgil","Gilbert",
    "Gillbert","Glum","Gomrund","Gorazin","Gottri","Gradnar","Grimli","Groth","Grunni","Guttri","Hadra","Halkenhaf",
    "Hargrim","Harrok","Heganbor","Hugrim","Josef","Kadrin","Kallon","Kargun","Kazadni","Kazador","Kazran","Kobalt",
    "Kragg","Kunn","Kurgan","Largs","Logan","Logazor","Lun","Molgo","Mordim","Morek","Morgrim","Norgrim","Okri","Oldor",
    "Rangni","Rorek","Rungni","Scotchel","Skag","Skaldor","Skalli","Skorri","Skorrigni","Snorri","Storri","Stotchel",
    "Sundrim","Sven","Svenner","Tekton","Thingrim","Thorgard","Thori","Throni","Thronni","Thrund","Thungni","Thurgrom",
    "Thyk","Ulfar","Ulther","Vikram","Vrangni","Yadri","Yanna","Yorri","Zamnil"];
const dwarfFemaleNames = ["Ailga","Ailvana","Balarika","Berta","Brigit","Brondra","Brunna","Dathina","Dimora","Elamina",
    "Fenna","Ferhelga","Friga","Gidona","Hilda","Hunni","Ingrid","Kalea","Karstin","Katanya","Kera","Kettra","Lenka",
    "Lorrena","Magda","Olga","Tarni","Tharma","Thomina","Trunni","Ulla","Vala","Valma","Vanyra","Zargona","Zylra"];
let dwarfSurnameFirst=["Amber","Autumn","Battle","Bear","Bitter","Black","Blunt","Boulder","Brane","Bright","Brittle",
    "Broad","Broken","Bronze","Brown","Cask","Cinder","Cliff","Coal","Cold","Common","Copper","Crag","Deep","Distant",
    "Ember","Far","Fiery","Fire","Flame","Flat","Flint","Forge","Full","Fuse","Gold","Golden","Grand","Granite","Gray",
    "Great","Grim","Grudge","Grumble","Hammer","Hill","Ingot","Iron","Keen","Keg","Krag","Lead","Light","Magma","Merry",
    "Metal","Mild","Mirth","Mithril","Mountain","Noble","Onyx","Plain","Proud","Regal","Rich","Rock","Rough","Rumble",
    "Shatter","Silver","Slender","Solid","Steel","Stone","Storm","Stout","Strong","Thunder","True"];
let dwarfSurnameSecond=["arm","armor","armour","axe","back","basher","beam","beard","bearer","belly","belt","bender",
    "bluff","bone","bough","brace","branch","brand","breaker","brew","brewer","bringer","brow","buckle","buster",
    "chaser","chest","chin","cloak","crag","crest","digger","dreamer","feet","finger","fire","fist","fists","flame",
    "foot","force","forge","forged","fury","grip","grog","guard","gut","hammer","hand","hank","head","heart","helm",
    "keeper","maker","mantle","mark","master","might","more","punch","rage","seeker","shaper","shield","shoulder",
    "shout","strength","strider","striker","surge","sworn","thane","walker","ward"];
let elfCommonFirst = ["Ae","Aes","Al","Ali","Am","An","Ast","Ath","Bel","Cal","Dor","El","Far","Fin","Gal","Im","Kor",
    "Li","Lin","Mal","Men","Mor","Sul","Sum","Tec","Thy","Tyr","Ullia"];
let elfCommonSecond = ["a","aeg","an","ari","ath","dia","dith","e","en","for","i","lan","lor","mar","nar","o","ol","ri",
    "sor","than","thar","u"];
let highElfMaleThird = ["andril","anel","bar","dial","dor","drian","dryan","elion","ellion","eren","eth","fin","hil",
    "ien","il","ion","irian","ith","lis","mor","naer","nil","nir","nor","nur","ric","riel","rik","ris","wing"];
let highElfFemaleThird = ["andrille","anelle","dora","dra","drielle","drya","elle","erena","erenne","ienne","ila",
    "iriana","irianne","lisa","mora","naera","nille","nira","nire","nora","ra","rielle"];
let highElfSurnameFirst = ["Ember","Fire","Foam","Golden","Silver","Spell","Fey","Stead","White","Far","Crest","Arc",
    "Dark","Charm","Gray","Lore"];
let highElfSurnameSecond = ["fell","born","heart","hair","spray","sign","farer","fast","mane","trader","rider","eye",
    "step","watch","binder"];
let woodElfMaleThird = ["anhu","arha","cha","dda","erth","han","ion","loc","noc","oth","ryn","stra","wyth","das","usco",
    "rat","ulgo"];
let woodElfFemaleThird = ["ara","ana","chae","ddil","essa","ina","iona","locia","na","onia","rel","strae","wythia",
    "ylla","mara","ainne","aethra","ita","astra"];
let woodElfSurnameFirst = ["Apple","Aspen","Bloom","Far","Fern","Fleet","Frost","Harrow","Lichen","Night","Oaken",
    "Pine","Shadow","Snow","Soft","Spring","Star","Still","Tree","Twice","Weave","White","Willow","Wind"];
let woodElfSurnameSecond = ["scrub","gate","heart","track","brook","river","weald","lay","branch","lock","vale",
    "stalker","grass","stone","light","water","shaper","watcher","shore","limb","rider","runner"];
let halflingMale = ["Adolphus (Addy)","Alfred (Al)","Bogodoc (Doc)","Ernestus (Ernie)","Ferdinand (Fred)",
    "Gadfast (Gad)","Heinricus (Rick)","Heironymus (Hiro)","Helembertus (Bert)","Jeronymus (Jerry)","Lambertus (Lam)",
    "Maximilian (Max)","Nicodemus (Nick)","Niklaus (Klaus)","Oleander (Ollie)","Phillipus (Pip)","Radmutch (Rad)",
    "Ramvoldus (Ram)","Taffinwick (Wick)","Theodosius (Theo)","Valentin (Val)","Verpasian (Peri)","Wattmutch (Wyatt)",
    "Winricus (Win)","Zacharius (Zack)"];
let halflingFemale = ["Amaryllis (Amy)","Antoniella (Anni)","Belladonna (Bell)","Camellia (Cam)","Charlize (Cherry)",
    "Charmaine (Cher)","Dezarina (Dizzy)","Elisabet (Lizzy)","Esmerelda (Esme)","Gwinston (Gwen)","Julianna (Jewel)",
    "Kathrin (Kat)","Lavinia (Nina)","Marigold (Mary)","Martina (Ma)","Minerva (Minny)","Petrilly (Lily)",
    "Primula (Prim)","Rosalita (Rosie)","Sabrina (Beanie)","Seraphina (Sara)","Susannah (Susie)","Thomasina (Tina)"];
let halflingSurnameFirst = ["Rum","Ash","Brandy","Hay","Short","Thorn","Down","Bramble","Moon","Summer","Elder","Swift",
    "Light","Thistle","Quick","Low","True","Under","Tea"];
let halflingSurnameSecond = ["bottom","cobble","snap","field","foot","side","belly","hare","wood","bottle","barrel",
    "step","sun","dance","flower","song","wich","wick","hill"];